M48
; DRILL file {KiCad (6.0.5)} date Tue Jun 14 18:11:54 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-14T18:11:54+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1575
%
G90
G05
T1
X1.6Y-2.6
X1.6Y-3.4
X1.6Y-4.2
X2.3772Y-5.3661
X2.4Y-2.6
X2.4Y-4.2
X2.4008Y-3.4004
X3.1772Y-5.3661
X3.2Y-2.6
X3.2Y-3.4
X3.2Y-4.2
T0
M30
