M48
; DRILL file {KiCad (6.0.5)} date Sat Jun  4 16:39:09 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-04T16:39:09+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1575
%
G90
G05
T1
X2.5Y-2.45
X2.5Y-3.25
X2.5Y-4.05
X3.2992Y-3.2496
X3.3Y-2.45
X3.3Y-4.05
X4.1Y-2.45
X4.1Y-3.25
X4.1Y-4.05
T0
M30
